### ISSUE TITLE
Expose DNSKEYs as well as DS Records

### ISSUE THREAD

**Issue by ShaneMcC** [mydnshost/mydnshost-frontend#12]
Some providers (Gandi...) want the actual DNSKEY record not the DS record when adding DNSSEC to their panel.

*sigh*

**Comment by greboid** [comment]
An example, Google provide the basic DS key for most people, with an expanded bit with more information for everyone else.  You could even do a popout modal for the further information bit to save changing the UI too much.
![step1](https://user-images.githubusercontent.com/189618/30785943-4af8e04a-a166-11e7-983b-b8f8a6909bdd.PNG)
![step2](https://user-images.githubusercontent.com/189618/30785944-4c72a744-a166-11e7-8944-0a20788e877e.PNG)

**Comment by ShaneMcC** [comment]
^^ The above commit basically implements exactly what google does above.
