### ISSUE TITLE
Gravatar opt-in/opt-out

### ISSUE THREAD

**Issue by ShaneMcC** [mydnshost/mydnshost-frontend#22]
Gravatar usage probably needs to be opt in, or at the very least opt-out able for annoying reasons.

**Comment by ShaneMcC** [comment]
For similar annoying reasons, we probably need to proxy gravatar requests.

**Comment by ShaneMcC** [comment]
Opt in/out seems pointless as the email is shared with other people if you share domains with them and they could just gravatar it themselves.

Maybe still do proxying to prevent the leak of who is looking at what gravatars.

**Comment by csmith** [comment]
> Opt in/out seems pointless as the email is shared with other people if you share domains with them and they could just gravatar it themselves.

Not sure that makes sense... Just because you consent to share with person A doesn't mean you consent to share with giant corporation B, even if there's a slim chance that A could go and give the data to B.

**Comment by ShaneMcC** [comment]
I still don't think I agree with needing this on mydnshost.co.uk, as I think my privacy policy covers it.

I have however now added support for arbitrary avatar urls with special-cased "gravatar" and "none" options which also then covers this issue.

Even though the code does allow arbitrary urls, we currently fail validation for the user on anything that isn't "gravatar" or "none".
