### ISSUE TITLE
Enable subresource integrity

### ISSUE THREAD

**Issue by csmith** [mydnshost/mydnshost-frontend#31]
The frontend should use SRI to ensure that the JavaScript isn't tampered with.

This is especially useful as it's loading JS from a third-party CDN.

https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by ShaneMcC** [comment]
Probably not gonna do this for our own JS/CSS any time soon, it's a bit more awkward.
