### ISSUE TITLE
Pasting into record field doesn't work correctly

### ISSUE THREAD

**Issue by csmith** [mydnshost/mydnshost-frontend#34]
When you paste into a record, it replaces the entire contents of the field instead of inserting text at the cursor position.

This is really annoying if you've typed something then try to paste something on the end.

Looks like the onPaste handler for trimming whitespace just blats the current value completely instead of appending the pasted + trimmed text.

**Comment by ShaneMcC** [comment]
Yes... Yes it will do this...
