### ISSUE TITLE
"Domain keys" section is confusing

### ISSUE THREAD

**Issue by csmith** [mydnshost/mydnshost-frontend#47]
![image](https://user-images.githubusercontent.com/189133/57091131-5c735280-6d00-11e9-9d8d-4d34df361a5e.png)

Domain Keys are obviously an e-mail thing, which is confusing. It should probably have the word "API" in it somewhere, and maybe a little bit of description/help text? It took me a minute to realise what this was and I knew already, so someone less familiar with the ins and outs of MyDnsHost is gonna have problems :)

**Comment by ShaneMcC** [comment]
https://github.com/mydnshost/mydnshost-frontend/commit/d68c29e7338c2cd0b27c96da1e76262a4291d8cb
