### ISSUE TITLE
Add mydnshost.co.uk to the HSTS preload list

### ISSUE THREAD

**Issue by csmith** [mydnshost/mydnshost-frontend#7]
Instructions and forms at https://hstspreload.org/

Having it in the preload list prevents downgrade attacks the first time a user access the site (i.e., a nasty middle-man could proxy the request and force them to use HTTP because they've never connected and received the HSTS header)

(Not really a frontend issue, but not sure where else to raise this?)

**Comment by ShaneMcC** [comment]
> Success
> mydnshost.co.uk is now pending inclusion in the HSTS preload list!
